cc_library(
    name = "error",
    srcs = [
        "Error.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "result",
    srcs = [
        "Result.h",
    ],
    visibility = ["//visibility:public"],
)
